// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARm5eVjrZ8JtSX5TMinYGI-t2Zynrcg3s',
    appId: '1:711163946311:android:6c8410e5f467aa38ae1862',
    messagingSenderId: '711163946311',
    projectId: 'admin-panel-app-e0ab9',
    databaseURL: 'https://admin-panel-app-e0ab9-default-rtdb.firebaseio.com',
    storageBucket: 'admin-panel-app-e0ab9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUK0VddFvfD0hSObv42OjcXBD0EU99Koc',
    appId: '1:711163946311:ios:870b2069de3dfb01ae1862',
    messagingSenderId: '711163946311',
    projectId: 'admin-panel-app-e0ab9',
    databaseURL: 'https://admin-panel-app-e0ab9-default-rtdb.firebaseio.com',
    storageBucket: 'admin-panel-app-e0ab9.appspot.com',
    androidClientId: '711163946311-roinh8vjtvff4q87dm6nb91k9irnuvab.apps.googleusercontent.com',
    iosClientId: '711163946311-at4ppsr59cjroadojuaegj0kvmq2urvc.apps.googleusercontent.com',
    iosBundleId: 'com.callpush.adsFirebase',
  );
}
